### ISSUE TITLE
Milestone 3 Task Trackers

### ISSUE THREAD

**Issue by huijuechen** [UBC-MDS/miniTidyR#16]
FOR R PACKAGE:

- [x] Write code of all 3 functions and make sure they pass the test cases we wrote.

- [x] Tasks for each of the 3 functions would be tracked in the issues below (all assigned to Milestone 2):
    - [`my_dropna`](https://github.com/UBC-MDS/miniTidyR/issues/15)
    - [`my_gather` ](https://github.com/UBC-MDS/miniTidyR/issues/10)
    - [`my_spread` ](https://github.com/UBC-MDS/miniTidyR/issues/11)

- [x] Code review of all 3 functions:
    - [`my_dropna` by Orphelia](https://github.com/UBC-MDS/miniTidyR/pull/14#discussion_r261478428)
    -  [`my_gather` by Iris](https://github.com/UBC-MDS/mini_tidy_python/pull/16#pullrequestreview-203539798)
    -  [`my_spread` by Juno](https://github.com/UBC-MDS/miniTidyR/pull/13#pullrequestreview-209454284)

- [x] Check the branch coverage of test suite for each function, provide documentation

- [x] Check if package works by user downloading and installing them from Github and use them in their own software development.

- [x] Choose and add a [Software License](https://github.com/UBC-MDS/miniTidyR/blob/master/LICENSE.md).

- [x] Update documentation for below if needed:
    - R package README (including usage and installation instructions)
    - functions
    - tests
    - vignette
